### PR TITLE
Switch to Zarr only

### PR DESCRIPTION
**Pull request by chris-allan**
In line with upstream bioformats2raw and raw2ometiff, switch to a Zarr only layout.

### CODE REVIEW

**Review by melissalinkert — APPROVED** [review]

**Comment by melissalinkert** [comment]
Last 3 commits have layout changes to work with raw2ometiff 0.3.0rc3 as discussed earlier.  Only nested data is written at the moment, but can make configurable.

**Comment by chris-allan** [comment]
@melissalinkert: Ready for re-review. Added `--nested` option to make things more configurable. Only did my testing on v2 of the Philips SDK. We'll probably need to watch out going forward with Python package versions as Python 3.6 is the latest supported version of the SDK at present and is only available on Ubuntu 18.04.

**Comment by melissalinkert** [comment]
Definitely had an easier time testing on Windows, especially since the Windows version of the Philips SDK allows Python 3.7.  ```--no-nested``` works as expected.  With ```--nested``` I see:

```
PS C:\Users\melissa> isyntax2raw.exe write_tiles .\data\bf-data-repo\warwick\2021-04-19\Images_for_Glencoe\81RLPN_S1_P.i
syntax data\81-isyntax-nested --nested
Traceback (most recent call last):
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\melissa\AppData\Local\Programs\Python\Python37\Scripts\isyntax2raw.exe\__main__.py", line 7, in <module
>
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\isyntax2raw\cli\isyntax2raw.py", line
84, in main
    cli()
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\isyntax2raw\cli\isyntax2raw.py", line
75, in write_tiles
    wt.write_label_image()
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\isyntax2raw\__init__.py", line 446, in
 write_label_image
    self.write_image_type("LABELIMAGE", 1)
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\isyntax2raw\__init__.py", line 477, in
 write_image_type
    tile[0, 0, channel] = band
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\zarr\core.py", line 1213, in __setitem
__
    self.set_basic_selection(selection, value, fields=fields)
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\zarr\core.py", line 1308, in set_basic
_selection
    return self._set_basic_selection_nd(selection, value, fields=fields)
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\zarr\core.py", line 1599, in _set_basi
c_selection_nd
    self._set_selection(indexer, value, fields=fields)
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\zarr\core.py", line 1672, in _set_sele
ction
    fields=fields)
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\zarr\core.py", line 1863, in _chunk_se
titems
    self.chunk_store.setitems(values)
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\zarr\storage.py", line 1098, in setite
ms
    self.map.setitems(values)
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\fsspec\mapping.py", line 111, in setit
ems
    self.fs.pipe(values)
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\fsspec\spec.py", line 673, in pipe
    self.pipe_file(self._strip_protocol(k), v, **kwargs)
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\fsspec\spec.py", line 653, in pipe_fil
e
    with self.open(path, "wb") as f:
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\fsspec\spec.py", line 948, in open
    **kwargs,
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\fsspec\implementations\local.py", line
 120, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\fsspec\implementations\local.py", line
 202, in __init__
    self._open()
  File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\fsspec\implementations\local.py", line
 207, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/melissa/data/81-isyntax-nested/1/0/0/0/0/0/0'
```

Adding ```auto_mkdir=True``` when constructing the ```FSStore``` seems to fix.  I would have expected the default to be nested (matching bioformats2raw), but it looks like the default is not nested.

**Comment by chris-allan** [comment]
👍

Should have those issues resolved now @melissalinkert.

**Comment by melissalinkert** [comment]
All looks good now, thanks.

**Comment by melissalinkert** [comment]
Last 2 commits look fine as well.

**Comment by ivicts** [comment]
> Definitely had an easier time testing on Windows, especially since the Windows version of the Philips SDK allows Python 3.7. `--no-nested` works as expected. With `--nested` I see:
> 
> ```
> PS C:\Users\melissa> isyntax2raw.exe write_tiles .\data\bf-data-repo\warwick\2021-04-19\Images_for_Glencoe\81RLPN_S1_P.i
> syntax data\81-isyntax-nested --nested
> Traceback (most recent call last):
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\melissa\AppData\Local\Programs\Python\Python37\Scripts\isyntax2raw.exe\__main__.py", line 7, in <module
> >
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\isyntax2raw\cli\isyntax2raw.py", line
> 84, in main
>     cli()
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\isyntax2raw\cli\isyntax2raw.py", line
> 75, in write_tiles
>     wt.write_label_image()
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\isyntax2raw\__init__.py", line 446, in
>  write_label_image
>     self.write_image_type("LABELIMAGE", 1)
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\isyntax2raw\__init__.py", line 477, in
>  write_image_type
>     tile[0, 0, channel] = band
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\zarr\core.py", line 1213, in __setitem
> __
>     self.set_basic_selection(selection, value, fields=fields)
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\zarr\core.py", line 1308, in set_basic
> _selection
>     return self._set_basic_selection_nd(selection, value, fields=fields)
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\zarr\core.py", line 1599, in _set_basi
> c_selection_nd
>     self._set_selection(indexer, value, fields=fields)
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\zarr\core.py", line 1672, in _set_sele
> ction
>     fields=fields)
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\zarr\core.py", line 1863, in _chunk_se
> titems
>     self.chunk_store.setitems(values)
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\zarr\storage.py", line 1098, in setite
> ms
>     self.map.setitems(values)
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\fsspec\mapping.py", line 111, in setit
> ems
>     self.fs.pipe(values)
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\fsspec\spec.py", line 673, in pipe
>     self.pipe_file(self._strip_protocol(k), v, **kwargs)
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\fsspec\spec.py", line 653, in pipe_fil
> e
>     with self.open(path, "wb") as f:
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\fsspec\spec.py", line 948, in open
>     **kwargs,
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\fsspec\implementations\local.py", line
>  120, in _open
>     return LocalFileOpener(path, mode, fs=self, **kwargs)
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\fsspec\implementations\local.py", line
>  202, in __init__
>     self._open()
>   File "c:\users\melissa\appdata\local\programs\python\python37\lib\site-packages\fsspec\implementations\local.py", line
>  207, in _open
>     self.f = open(self.path, mode=self.mode)
> FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/melissa/data/81-isyntax-nested/1/0/0/0/0/0/0'
> ```
> 
> Adding `auto_mkdir=True` when constructing the `FSStore` seems to fix. I would have expected the default to be nested (matching bioformats2raw), but it looks like the default is not nested.

Hello, I have the same issue as this one with the isyntax2raw 0.6.0, I have chekced that 'auto_mkdir=True' is set on 'FSStore', but I still have an issue with this. Any pointers regarding this?

Thank you in advance.
Regards,
ivicts

**Pull request merged**
